# Generated by Django 3.2.25 on 2026-05-12 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_lead_deleted_at'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='lead',
            field=models.ForeignKey(help_text='Lead vinculado. PROTECT impede exclusão acidental de leads com contratos: contrato assinado preserva a relação documental para fins fiscais/LGPD. Para excluir, finalize ou exclua o contrato primeiro.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.lead', verbose_name='Lead'),
        ),
    ]
