# Generated by Django 3.2.25 on 2026-05-12 02:55

import apps.contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='body',
            field=models.TextField(blank=True, help_text="Substitui o campo 'content' legado. Aceita HTML formatado.", verbose_name='Corpo do contrato (rich)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='contract',
            name='footer_content',
            field=models.TextField(blank=True, verbose_name='Rodapé (texto rich)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='footer_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.contracts.models._contract_footer_image_path, verbose_name='Imagem do rodapé'),
        ),
        migrations.AddField(
            model_name='contract',
            name='header_content',
            field=models.TextField(blank=True, verbose_name='Cabeçalho (texto rich)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='header_image',
            field=models.ImageField(blank=True, help_text='PNG, JPG ou WEBP. Máx. 2MB. Se vazio, herda do template.', null=True, upload_to=apps.contracts.models._contract_header_image_path, verbose_name='Imagem do cabeçalho'),
        ),
        migrations.AddField(
            model_name='contract',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='Introdução'),
        ),
        migrations.AddField(
            model_name='contract',
            name='terms',
            field=models.TextField(blank=True, verbose_name='Termos e condições'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='body',
            field=models.TextField(blank=True, help_text="Substitui o campo 'content' legado.", verbose_name='Corpo do contrato (rich)'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='footer_content',
            field=models.TextField(blank=True, verbose_name='Rodapé (texto rich)'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='footer_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.contracts.models._contract_footer_image_path, verbose_name='Imagem do rodapé'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='header_content',
            field=models.TextField(blank=True, verbose_name='Cabeçalho (texto rich)'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='header_image',
            field=models.ImageField(blank=True, help_text='PNG, JPG ou WEBP. Máx. 2MB.', null=True, upload_to=apps.contracts.models._contract_header_image_path, verbose_name='Imagem do cabeçalho'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='Introdução padrão'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='terms',
            field=models.TextField(blank=True, verbose_name='Termos padrão'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='content',
            field=models.TextField(blank=True, help_text="Campo legado. Use 'body' (rich-text) para novos contratos.", verbose_name='Conteúdo (legado)'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='content',
            field=models.TextField(blank=True, help_text="Campo legado. Use 'body' (rich-text) para novos templates.", verbose_name='Conteúdo (legado)'),
        ),
    ]
