# Generated by Django 3.2.25 on 2026-05-12 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_rich_fields_and_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('signed', 'Assinado'), ('active', 'Ativo'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], max_length=20, verbose_name='De')),
                ('to_status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('signed', 'Assinado'), ('active', 'Ativo'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], max_length=20, verbose_name='Para')),
                ('note', models.TextField(blank=True, verbose_name='Observação')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='contracts.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Histórico de Status do Contrato',
                'verbose_name_plural': 'Históricos de Status dos Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contractstatushistory',
            index=models.Index(fields=['contract', '-created_at'], name='contracts_c_contrac_771526_idx'),
        ),
    ]
