# Generated by Django 5.1.15 on 2026-05-23 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_public_token_and_send_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID para URL pública /c/<token>/ (envio por WhatsApp).', unique=True, verbose_name='Token público'),
        ),
    ]
