# Generated by Django 3.2.25 on 2026-05-09 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=200, verbose_name='Servidor SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='Porta')),
                ('username', models.CharField(max_length=200, verbose_name='Usuário')),
                ('password_encrypted', models.TextField(blank=True, editable=False, verbose_name='Senha (criptografada)')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('timeout_seconds', models.PositiveIntegerField(default=20, verbose_name='Timeout (segundos)')),
                ('from_email', models.EmailField(max_length=200, verbose_name='E-mail de origem')),
                ('from_name', models.CharField(blank=True, help_text='Aparece como remetente. Em branco = nome da empresa.', max_length=200, verbose_name='Nome de exibição')),
                ('is_active', models.BooleanField(default=True, help_text='Desative para temporariamente cair no SMTP global.', verbose_name='Ativa')),
                ('last_tested_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Último teste')),
                ('last_test_ok', models.BooleanField(default=False, editable=False, verbose_name='Último teste OK')),
                ('last_test_error', models.TextField(blank=True, editable=False, verbose_name='Erro no último teste')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='accounts.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configurações de E-mail',
            },
        ),
    ]
