# Generated by Django 3.2.25 on 2026-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empresa_email_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaemailconfig',
            name='imap_active',
            field=models.BooleanField(default=False, help_text='Liga o poller que puxa novos e-mails para a inbox.', verbose_name='Recepção IMAP ativa'),
        ),
        migrations.AddField(
            model_name='empresaemailconfig',
            name='imap_folder',
            field=models.CharField(default='INBOX', help_text="Geralmente 'INBOX'.", max_length=80, verbose_name='Pasta IMAP'),
        ),
        migrations.AddField(
            model_name='empresaemailconfig',
            name='imap_host',
            field=models.CharField(blank=True, help_text='Deixe vazio para desabilitar recepção (apenas envio).', max_length=200, verbose_name='Servidor IMAP'),
        ),
        migrations.AddField(
            model_name='empresaemailconfig',
            name='imap_last_poll_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última varredura IMAP'),
        ),
        migrations.AddField(
            model_name='empresaemailconfig',
            name='imap_last_poll_error',
            field=models.TextField(blank=True, editable=False, verbose_name='Erro na última varredura'),
        ),
        migrations.AddField(
            model_name='empresaemailconfig',
            name='imap_last_poll_ok',
            field=models.BooleanField(default=False, editable=False, verbose_name='Última varredura OK'),
        ),
        migrations.AddField(
            model_name='empresaemailconfig',
            name='imap_port',
            field=models.PositiveIntegerField(default=993, help_text='993 (SSL/IMAPS) ou 143 (STARTTLS).', verbose_name='Porta IMAP'),
        ),
        migrations.AddField(
            model_name='empresaemailconfig',
            name='imap_use_ssl',
            field=models.BooleanField(default=True, help_text='True para porta 993 (IMAPS). False para 143 com STARTTLS.', verbose_name='IMAP SSL'),
        ),
    ]
