# Generated by Django 5.1.15 on 2026-06-02 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imap_fields'),
        ('operations', '0008_jobrole_hourrate_workordertimelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='operations.jobrole', verbose_name='Função / Cargo'),
        ),
    ]
