# Generated by Django 5.1.15 on 2026-05-07 13:37

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='Pode ser informado com ou sem máscara.', max_length=18, validators=[apps.core.validators.validate_cpf_or_cnpj], verbose_name='CPF/CNPJ')),
                ('cpf_cnpj_normalized', models.CharField(blank=True, db_index=True, editable=False, max_length=14)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Empresa do contato')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('source', models.CharField(blank=True, choices=[('site', 'Site'), ('indicacao', 'Indicação'), ('google', 'Google'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('chatbot', 'Chatbot'), ('import', 'Importação'), ('outro', 'Outro')], max_length=20, verbose_name='Origem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['empresa', 'name'], name='contacts_co_empresa_725b72_idx'), models.Index(fields=['empresa', 'phone'], name='contacts_co_empresa_a6b0b9_idx'), models.Index(fields=['empresa', 'email'], name='contacts_co_empresa_e8ab8a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cpf_cnpj_normalized', ''), _negated=True), fields=('empresa', 'cpf_cnpj_normalized'), name='contacts_unique_doc_per_empresa')],
            },
        ),
    ]
