# Generated by Django 5.1.15 on 2026-06-02 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('celular', 'Celular'), ('whatsapp', 'WhatsApp'), ('comercial', 'Comercial'), ('fixo', 'Fixo'), ('outro', 'Outro')], default='celular', max_length=20, verbose_name='Tipo')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('is_principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('order', models.PositiveIntegerField(default=0)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='contacts.contato', verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Telefone do contato',
                'verbose_name_plural': 'Telefones do contato',
                'ordering': ['order', 'id'],
            },
        ),
    ]
