# Generated by Django 5.1.15 on 2026-06-02 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_membership_job_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Ativo')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Número WhatsApp dedicado ao assistente (E.164).', max_length=32)),
                ('llm_provider', models.CharField(choices=[('none', 'Nenhum'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='none', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('system_prompt', models.TextField(blank=True)),
                ('api_key_encrypted', models.TextField(blank=True, editable=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Configuração do Assistente IA',
                'verbose_name_plural': 'Configurações do Assistente IA',
                'constraints': [models.UniqueConstraint(fields=('empresa',), name='assistant_config_unique_per_empresa')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=20)),
                ('status', models.CharField(choices=[('not_connected', 'Não conectado'), ('connected', 'Conectado'), ('expired', 'Expirado'), ('error', 'Erro')], default='not_connected', max_length=20)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('access_token_encrypted', models.TextField(blank=True, editable=False)),
                ('refresh_token_encrypted', models.TextField(blank=True, editable=False)),
                ('token_type', models.CharField(blank=True, max_length=40)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, editable=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Conexão de Integração',
                'verbose_name_plural': 'Conexões de Integração',
                'ordering': ['empresa', 'provider'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'provider'), name='integration_connection_unique_provider_per_empresa')],
            },
        ),
    ]
