# Generated by Django 5.1.15 on 2026-04-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialentry',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Indica que este lançamento foi criado automaticamente a partir de uma proposta/contrato. Pode ser editado manualmente.', verbose_name='Gerado automaticamente'),
        ),
    ]
