# Generated by Django 3.2.25 on 2026-04-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0002_financialentry_auto_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialentry',
            name='payment_ref',
            field=models.CharField(blank=True, help_text='Código de barras, ID Pix, ou referência externa', max_length=200, verbose_name='Referência de pagamento'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Ex: Conta PJ Itaú', max_length=100, verbose_name='Apelido')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banco')),
                ('bank_code', models.CharField(blank=True, max_length=10, verbose_name='Código do banco')),
                ('agency', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('account_number', models.CharField(blank=True, max_length=30, verbose_name='Número da conta')),
                ('account_type', models.CharField(choices=[('checking', 'Conta Corrente'), ('savings', 'Poupança'), ('payment', 'Conta de Pagamento')], default='checking', max_length=20, verbose_name='Tipo de conta')),
                ('person_type', models.CharField(choices=[('pj', 'Pessoa Jurídica'), ('pf', 'Pessoa Física')], default='pj', max_length=5, verbose_name='Tipo de pessoa')),
                ('holder_name', models.CharField(blank=True, max_length=200, verbose_name='Titular')),
                ('holder_document', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ do titular')),
                ('pix_key', models.CharField(blank=True, help_text='CPF, CNPJ, e-mail, telefone ou chave aleatória', max_length=200, verbose_name='Chave Pix')),
                ('is_default', models.BooleanField(default=False, help_text='Conta usada como padrão em novos lançamentos', verbose_name='Conta padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_bankaccount_set', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='financialentry',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.bankaccount', verbose_name='Conta Bancária'),
        ),
    ]
