# Generated by Django 5.1.15 on 2026-05-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imap_fields'),
        ('crm', '0012_lead_won_finance_rv06'),
        ('finance', '0003_bank_account_and_entry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialentry',
            name='related_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries', to='crm.lead', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa'),
        ),
    ]
