# Generated by Django 5.1.15 on 2026-06-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_membership_job_role'),
        ('finance', '0004_lead_won_finance_rv06'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('sandbox', 'Sandbox (demonstração)'), ('manual', 'Importação manual (CSV/OFX)'), ('pluggy', 'Pluggy'), ('belvo', 'Belvo')], default='manual', max_length=20, verbose_name='Provedor')),
                ('status', models.CharField(choices=[('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('error', 'Erro')], default='connected', max_length=20, verbose_name='Status')),
                ('credentials_encrypted', models.TextField(blank=True, help_text='Token/credenciais do agregador, cifrados com Fernet.', verbose_name='Credenciais (cifradas)')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='finance.bankaccount', verbose_name='Conta bancária')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Conexão bancária (Open Finance)',
                'verbose_name_plural': 'Conexões bancárias (Open Finance)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, help_text='Identificador da transação no banco/agregador (idempotência).', max_length=200, verbose_name='ID externo')),
                ('date', models.DateField(verbose_name='Data')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Descrição')),
                ('direction', models.CharField(choices=[('credit', 'Entrada'), ('debit', 'Saída')], max_length=10, verbose_name='Sentido')),
                ('classification_status', models.CharField(choices=[('pending', 'Pendente'), ('classified', 'Classificada'), ('ignored', 'Ignorada')], default='pending', max_length=12, verbose_name='Classificação')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload bruto')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_transactions', to='finance.bankaccount', verbose_name='Conta bancária')),
                ('classified_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.financialentry', verbose_name='Lançamento gerado')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.bankconnection', verbose_name='Conexão')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Movimentação importada',
                'verbose_name_plural': 'Movimentações importadas',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['empresa', 'classification_status', '-date'], name='finance_imp_empresa_abb8e2_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'external_id'), name='uniq_imported_txn_empresa_external_id')],
            },
        ),
    ]
