# Generated by Django 5.1.15 on 2026-06-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_membership_job_role'),
        ('finance', '0005_bankconnection_importedtransaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankconnection',
            constraint=models.UniqueConstraint(fields=('empresa', 'provider'), name='uniq_bankconnection_empresa_provider'),
        ),
    ]
