# Generated by Django 5.1.15 on 2026-03-22 04:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=50, verbose_name='Número')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('introduction', models.TextField(blank=True, verbose_name='Introdução')),
                ('terms', models.TextField(blank=True, verbose_name='Termos e Condições')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('viewed', 'Visualizada'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('expired', 'Expirada')], default='draft', max_length=20, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Desconto (%)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válida até')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada em')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceita em')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejeitada em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='crm.lead', verbose_name='Lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.opportunity', verbose_name='Oportunidade')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('details', models.TextField(blank=True, verbose_name='Detalhes')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantidade')),
                ('unit', models.CharField(default='un', max_length=20, verbose_name='Unidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Unitário')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proposals.proposal', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Item da Proposta',
                'verbose_name_plural': 'Itens da Proposta',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProposalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('header_content', models.TextField(blank=True, verbose_name='Conteúdo do Cabeçalho')),
                ('footer_content', models.TextField(blank=True, verbose_name='Conteúdo do Rodapé')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Template de Proposta',
                'verbose_name_plural': 'Templates de Proposta',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='proposals.proposaltemplate', verbose_name='Template'),
        ),
    ]
