# Generated by Django 5.1.15 on 2026-03-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='installment_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Parcelas'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_installment',
            field=models.BooleanField(default=False, verbose_name='Parcelado'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('transferencia', 'Transferência'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], max_length=50, verbose_name='Forma de Pagamento'),
        ),
    ]
