# Generated by Django 5.1.15 on 2026-04-04 20:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_proposal_installment_count_proposal_is_installment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltemplate',
            name='default_installment_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Parcelas padrão'),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='default_is_installment',
            field=models.BooleanField(default=False, verbose_name='Parcelado por padrão'),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Forma de pagamento padrão'),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='Introdução padrão'),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='terms',
            field=models.TextField(blank=True, verbose_name='Termos padrão'),
        ),
        migrations.AlterField(
            model_name='proposaltemplate',
            name='content',
            field=models.TextField(blank=True, verbose_name='Conteúdo'),
        ),
        migrations.CreateModel(
            name='ProposalTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('details', models.TextField(blank=True, verbose_name='Detalhes')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantidade')),
                ('unit', models.CharField(default='un', max_length=20, verbose_name='Unidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço Unitário')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_items', to='proposals.proposaltemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Item do Template',
                'verbose_name_plural': 'Itens do Template',
                'ordering': ['order', 'id'],
            },
        ),
    ]
