# Generated by Django 3.2.25 on 2026-05-08 22:30

import apps.proposals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposaltemplate_default_installment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='body',
            field=models.TextField(blank=True, verbose_name='Corpo da proposta'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='header_image',
            field=models.ImageField(blank=True, help_text='PNG, JPG ou WEBP. Máx. 2MB. Se vazio, herda do template ou da empresa.', null=True, upload_to=apps.proposals.models._proposal_header_image_path, verbose_name='Imagem do cabeçalho (logo)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='use_template_header_image',
            field=models.BooleanField(default=True, help_text='Se ativo, herda imagem do template/empresa quando esta proposta não tem própria.', verbose_name='Usar imagem do template'),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='header_image',
            field=models.ImageField(blank=True, help_text='PNG, JPG ou WEBP. Máx. 2MB.', null=True, upload_to=apps.proposals.models._proposal_header_image_path, verbose_name='Imagem do cabeçalho (logo)'),
        ),
    ]
