# Generated by Django 3.2.25 on 2026-05-08 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0004_rich_text_and_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('viewed', 'Visualizada'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ProposalStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('viewed', 'Visualizada'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], max_length=20, verbose_name='De')),
                ('to_status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('viewed', 'Visualizada'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], max_length=20, verbose_name='Para')),
                ('note', models.TextField(blank=True, verbose_name='Observação')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='proposals.proposal', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Histórico de Status da Proposta',
                'verbose_name_plural': 'Históricos de Status das Propostas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='proposalstatushistory',
            index=models.Index(fields=['proposal', '-created_at'], name='proposals_p_proposa_0d2065_idx'),
        ),
    ]
