# Generated by Django 3.2.25 on 2026-05-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_servico_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Excluído em'),
        ),
    ]
