# Generated by Django 3.2.25 on 2026-05-12 11:42

import apps.proposals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_forma_pagamento_global_and_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltemplate',
            name='footer_image',
            field=models.ImageField(blank=True, help_text='PNG, JPG ou WEBP. Máx. 2MB.', null=True, upload_to=apps.proposals.models._proposal_footer_image_path, verbose_name='Imagem do rodapé (logo/identidade)'),
        ),
    ]
