# Generated by Django 5.1.15 on 2026-05-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_rename_servico_cadastrado_rv06'),
        ('proposals', '0010_proposaltemplate_footer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='operations.servicetype', verbose_name='Serviço Cadastrado'),
        ),
    ]
