# Generated by Django 3.2.25 on 2026-05-12 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_empresa_email_config'),
        ('chatbot', '0012_h_node_id_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
        ('crm', '0010_lead_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em atendimento'), ('waiting', 'Aguardando cliente'), ('closed', 'Encerrada')], default='open', max_length=20, verbose_name='Status')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Última mensagem em')),
                ('last_message_preview', models.CharField(blank=True, help_text='Texto da última mensagem (truncado).', max_length=200, verbose_name='Prévia')),
                ('last_message_direction', models.CharField(blank=True, max_length=10, verbose_name='Direção da última')),
                ('last_message_channel', models.CharField(blank=True, max_length=20, verbose_name='Canal da última')),
                ('unread_count', models.PositiveIntegerField(default=0, help_text='Inbounds desde o último readall.', verbose_name='Mensagens não lidas')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Atribuída para')),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='contacts.contato', verbose_name='Contato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications_conversation_set', to='accounts.empresa')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='crm.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('inbound', 'Recebida'), ('outbound', 'Enviada'), ('system', 'Sistema')], max_length=10, verbose_name='Direção')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('webchat', 'WebChat'), ('sms', 'SMS'), ('internal_note', 'Nota interna')], max_length=20, verbose_name='Canal')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Anexos, botões, raw provider data, metadados.', verbose_name='Payload')),
                ('sender_external_id', models.CharField(blank=True, help_text='Telefone, e-mail ou JID de origem (inbound).', max_length=120, verbose_name='ID externo')),
                ('sender_name', models.CharField(blank=True, max_length=120, verbose_name='Nome externo')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou'), ('na', '—')], default='na', max_length=12, verbose_name='Status de entrega')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='Erro de entrega')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversation', verbose_name='Conversa')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_conversation_messages', to=settings.AUTH_USER_MODEL, verbose_name='Enviada por (atendente)')),
                ('triggered_by_chatbot_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages', to='chatbot.chatbotsession', verbose_name='Disparada por sessão do bot')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['conversation', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='communicati_convers_c64725_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['direction', 'channel', '-created_at'], name='communicati_directi_18ae92_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['empresa', 'status', '-last_message_at'], name='communicati_empresa_7fa9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_to', '-last_message_at'], name='communicati_assigne_018a5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('empresa', 'lead'), name='communications_conversation_unique_empresa_lead'),
        ),
    ]
