# Generated by Django 5.1.15 on 2026-05-12 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imap_fields'),
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('message_inbound', 'Nova mensagem recebida'), ('conversation_assigned', 'Conversa atribuída a você'), ('lead_new', 'Novo lead'), ('proposal_accepted', 'Proposta aceita'), ('contract_signed', 'Contrato assinado'), ('system', 'Sistema')], default='system', max_length=40, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('body', models.TextField(blank=True, verbose_name='Corpo')),
                ('url', models.CharField(blank=True, help_text='Caminho relativo (ex.: /communications/inbox/42/).', max_length=500, verbose_name='URL de ação')),
                ('icon', models.CharField(blank=True, help_text="Nome do heroicon (ex.: 'envelope', 'user-plus').", max_length=40, verbose_name='Ícone')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Dados adicionais para deep-link, contadores, etc.', verbose_name='Payload')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('empresa', models.ForeignKey(blank=True, help_text='Tenant; null para notificações pessoais (sistema).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='communicati_user_id_b6e654_idx'), models.Index(fields=['user', 'read_at', '-created_at'], name='communicati_user_id_802108_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=200, verbose_name='Chave P256DH')),
                ('auth', models.CharField(max_length=80, verbose_name='Auth')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Push',
                'verbose_name_plural': 'Subscriptions Push',
                'indexes': [models.Index(fields=['user', '-created_at'], name='communicati_user_id_3e8623_idx')],
            },
        ),
    ]
