# Generated by Django 5.1.15 on 2026-05-12 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imap_fields'),
        ('communications', '0002_alter_conversation_empresa_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('shortcut', models.CharField(blank=True, help_text="Atalho digitável (ex.: 'ola', 'preco'). Sem espaços.", max_length=40, verbose_name='Atalho')),
                ('category', models.CharField(choices=[('greeting', 'Saudação'), ('followup', 'Follow-up'), ('proposal', 'Proposta'), ('closing', 'Encerramento'), ('objection', 'Objeção'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Categoria')),
                ('channel', models.CharField(choices=[('any', 'Qualquer canal'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('internal_note', 'Nota interna')], default='any', max_length=20, verbose_name='Canal')),
                ('content', models.TextField(help_text='Suporta {{ lead.name }}, {{ contato.name }}, {{ empresa.name }}, {{ user.first_name }}, {{ now.date }}.', verbose_name='Conteúdo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False, help_text='Contador de quantas vezes foi inserido em conversas.', verbose_name='Uso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Template de mensagem',
                'verbose_name_plural': 'Templates de mensagem',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['empresa', 'is_active', 'category'], name='communicati_empresa_4cbdf9_idx'), models.Index(fields=['empresa', 'shortcut'], name='communicati_empresa_d8a503_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('shortcut', ''), _negated=True), fields=('empresa', 'shortcut'), name='msg_template_unique_shortcut_per_empresa')],
            },
        ),
    ]
