# Generated by Django 5.1.15 on 2026-05-23 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_messagetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='bot_paused',
            field=models.BooleanField(default=False, help_text="Quando True, o chatbot NÃO responde mais nesta conversa. Setado automaticamente quando um atendente envia mensagem manual. Pode ser revertido via botão 'Devolver ao bot'.", verbose_name='Bot pausado'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='bot_paused_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp em que o atendente assumiu o controle.', null=True, verbose_name='Bot pausado em'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='bot_paused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paused_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Pausado por'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, help_text='Caminho relativo (ex.: /inbox/42/).', max_length=500, verbose_name='URL de ação'),
        ),
    ]
