# Generated by Django 5.1.15 on 2026-05-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_bot_paused_rv06'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message_inbound', 'Nova mensagem recebida'), ('conversation_assigned', 'Conversa atribuída a você'), ('lead_new', 'Novo lead'), ('lead_won', 'Lead ganho'), ('proposal_accepted', 'Proposta aceita'), ('contract_signed', 'Contrato assinado'), ('system', 'Sistema')], default='system', max_length=40, verbose_name='Tipo'),
        ),
    ]
