# Generated by Django 5.1.15 on 2026-06-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_notif_lead_won_rv06'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message_inbound', 'Nova mensagem recebida'), ('conversation_assigned', 'Conversa atribuída a você'), ('lead_new', 'Novo lead'), ('lead_won', 'Lead ganho'), ('proposal_accepted', 'Proposta aceita'), ('contract_signed', 'Contrato assinado'), ('proposal_sent', 'Proposta enviada'), ('contract_sent', 'Contrato enviado'), ('lead_moved', 'Lead movimentado'), ('service_started', 'Serviço iniciado'), ('service_completed', 'Serviço concluído'), ('lead_followup', 'Follow-up de lead pendente'), ('system', 'Sistema')], default='system', max_length=40, verbose_name='Tipo'),
        ),
    ]
