# Generated by Django 5.1.15 on 2026-06-03 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_digest', models.BooleanField(default=True, help_text='Receber um e-mail diário com as notificações não lidas.', verbose_name='Resumo diário por e-mail')),
                ('web_push', models.BooleanField(default=True, help_text='Receber notificações push no navegador, mesmo com a aba fechada.', verbose_name='Notificações no navegador')),
                ('muted_types', models.JSONField(blank=True, default=list, help_text='Tipos de evento que o usuário optou por não receber.', verbose_name='Tipos silenciados')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência de notificação',
                'verbose_name_plural': 'Preferências de notificação',
            },
        ),
    ]
