# Generated by Django 5.1.15 on 2026-06-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_notificationpreference'),
        ('crm', '0015_followupsettings_leadfollowupreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='crm.lead', verbose_name='Lead relacionado'),
        ),
    ]
