# Generated by Django 3.2.25 on 2026-04-07 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('webhook_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token do Webhook')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('webchat', 'WebChat'), ('telegram', 'Telegram')], default='whatsapp', max_length=20, verbose_name='Canal')),
                ('welcome_message', models.TextField(default='Olá! Seja bem-vindo(a). Vou ajudá-lo(a) com algumas perguntas rápidas.', verbose_name='Mensagem de boas-vindas')),
                ('fallback_message', models.TextField(default='Desculpe, não entendi. Pode repetir?', verbose_name='Mensagem de fallback')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_chatbotflow_set', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Fluxo de Chatbot',
                'verbose_name_plural': 'Fluxos de Chatbot',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('question_text', models.TextField(verbose_name='Pergunta')),
                ('step_type', models.CharField(choices=[('text', 'Texto livre'), ('choice', 'Escolha'), ('email', 'E-mail'), ('phone', 'Telefone'), ('name', 'Nome'), ('company', 'Empresa')], default='text', max_length=20, verbose_name='Tipo')),
                ('lead_field_mapping', models.CharField(blank=True, choices=[('name', 'Nome'), ('email', 'E-mail'), ('phone', 'Telefone'), ('company', 'Empresa'), ('notes', 'Observações')], help_text='Campo do lead que receberá a resposta.', max_length=50, verbose_name='Campo do Lead')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='chatbot.chatbotflow', verbose_name='Fluxo')),
            ],
            options={
                'verbose_name': 'Passo do Chatbot',
                'verbose_name_plural': 'Passos do Chatbot',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=200, verbose_name='Texto da opção')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('next_step', models.ForeignKey(blank=True, help_text='Se vazio, avança para o próximo passo na ordem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_choices', to='chatbot.chatbotstep', verbose_name='Próximo passo')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='chatbot.chatbotstep', verbose_name='Passo')),
            ],
            options={
                'verbose_name': 'Opção do Chatbot',
                'verbose_name_plural': 'Opções do Chatbot',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('on_complete', 'Ao completar'), ('on_timeout', 'Timeout'), ('on_keyword', 'Palavra-chave')], default='on_complete', max_length=20, verbose_name='Gatilho')),
                ('action_type', models.CharField(choices=[('create_lead', 'Criar lead'), ('notify_user', 'Notificar usuário'), ('send_message', 'Enviar mensagem')], default='create_lead', max_length=20, verbose_name='Tipo de ação')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Parâmetros da ação em JSON.', verbose_name='Configuração')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='chatbot.chatbotflow', verbose_name='Fluxo')),
            ],
            options={
                'verbose_name': 'Ação do Chatbot',
                'verbose_name_plural': 'Ações do Chatbot',
                'ordering': ['trigger'],
            },
        ),
    ]
