# Generated by Django 3.2.25 on 2026-04-14 02:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_external_ref'),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Chave da sessão')),
                ('lead_data', models.JSONField(blank=True, default=dict, verbose_name='Dados coletados')),
                ('channel', models.CharField(default='webchat', max_length=20, verbose_name='Canal')),
                ('sender_id', models.CharField(blank=True, max_length=255, verbose_name='ID do remetente')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluída'), ('expired', 'Expirada')], default='active', max_length=20, verbose_name='Status')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatbotstep', verbose_name='Passo atual')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chatbot.chatbotflow', verbose_name='Fluxo')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_sessions', to='crm.lead', verbose_name='Lead criado')),
            ],
            options={
                'verbose_name': 'Sessão do Chatbot',
                'verbose_name_plural': 'Sessões do Chatbot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatbotsession',
            index=models.Index(fields=['flow', 'status'], name='chatbot_cha_flow_id_c54aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotsession',
            index=models.Index(fields=['session_key'], name='chatbot_cha_session_6d6ce3_idx'),
        ),
    ]
