# Generated by Django 3.2.25 on 2026-04-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chatbot', '0002_auto_20260413_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_name', models.CharField(help_text='Identificador único desta instância na Evolution API (ex: empresa-a-whatsapp).', max_length=100, unique=True, verbose_name='Nome da instância')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Número conectado')),
                ('api_url', models.URLField(blank=True, help_text='Deixe em branco para usar a URL global configurada no servidor.', verbose_name='URL da Evolution API')),
                ('api_key', models.CharField(blank=True, help_text='Deixe em branco para usar a chave global configurada no servidor.', max_length=200, verbose_name='API Key')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Conectado')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='Conectado em')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='accounts.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuracao WhatsApp',
                'verbose_name_plural': 'Configuracoes WhatsApp',
            },
        ),
    ]
