# Generated by Django 3.2.25 on 2026-04-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_whatsapp_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='instance_token',
            field=models.CharField(blank=True, help_text='Gerado automaticamente pela Evolution API ao criar a instância.', max_length=200, verbose_name='Token da Instância'),
        ),
    ]
