# Generated by Django 3.2.25 on 2026-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_whatsapp_config_instance_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotstep',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Se marcado, encerra o fluxo ao responder este passo (útil para branching).', verbose_name='Passo terminal'),
        ),
    ]
