# Generated by Django 5.1.15 on 2026-05-07 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chatbot', '0005_add_step_is_final'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotflow',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Fluxo de Chatbot', 'verbose_name_plural': 'Fluxos de Chatbot'},
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='cooldown_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Tempo mínimo entre dois disparos do mesmo fluxo para a mesma sessão.', verbose_name='Cooldown (minutos)'),
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='exclusive',
            field=models.BooleanField(default=True, help_text='Quando ativo, bloqueia outros fluxos enquanto este estiver em andamento.', verbose_name='Exclusivo'),
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='inactivity_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Disparar após X minutos sem resposta do cliente.', null=True, verbose_name='Inatividade (minutos)'),
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Menor valor = maior prioridade. Empate vai por mais recente.', verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='trigger_keywords',
            field=models.CharField(blank=True, help_text="Separadas por vírgula. Aplica-se quando 'Tipo de gatilho' = palavra-chave.", max_length=500, verbose_name='Palavras-chave'),
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='trigger_type',
            field=models.CharField(choices=[('first_message', 'Primeira mensagem do cliente'), ('keyword', 'Palavra-chave'), ('inactivity', 'Inatividade'), ('manual', 'Manual / API')], default='first_message', max_length=20, verbose_name='Tipo de gatilho'),
        ),
        migrations.AlterField(
            model_name='chatbotflow',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa'),
        ),
        migrations.AlterField(
            model_name='chatbotflow',
            name='welcome_message',
            field=models.TextField(default='Olá! Seja bem-vindo(a). Vou ajudá-lo(a) com algumas perguntas rápidas.', help_text='Texto enviado ao iniciar o fluxo (antes do primeiro passo).', verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='chatbotstep',
            name='lead_field_mapping',
            field=models.CharField(blank=True, choices=[('name', 'Nome'), ('email', 'E-mail'), ('phone', 'Telefone'), ('company', 'Empresa'), ('cpf_cnpj', 'CPF/CNPJ'), ('notes', 'Observações')], help_text='Campo do lead que receberá a resposta.', max_length=50, verbose_name='Campo do Lead'),
        ),
        migrations.AlterField(
            model_name='chatbotstep',
            name='step_type',
            field=models.CharField(choices=[('text', 'Texto livre'), ('choice', 'Escolha'), ('email', 'E-mail'), ('phone', 'Telefone'), ('name', 'Nome'), ('company', 'Empresa'), ('document', 'CPF/CNPJ')], default='text', max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ChatbotFlowDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_id', models.CharField(max_length=255, verbose_name='Sender ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Disparado em')),
                ('reason', models.CharField(help_text="Ex.: 'first_message', 'inactivity 180min', 'blocked_by:flow_X'.", max_length=200, verbose_name='Motivo')),
                ('blocked', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='chatbot.chatbotflow', verbose_name='Fluxo')),
            ],
            options={
                'verbose_name': 'Disparo de Fluxo',
                'verbose_name_plural': 'Disparos de Fluxo',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['empresa', 'flow', '-triggered_at'], name='chatbot_cha_empresa_b4c416_idx'), models.Index(fields=['sender_id', '-triggered_at'], name='chatbot_cha_sender__c6846b_idx')],
            },
        ),
    ]
