# Generated by Django 3.2.25 on 2026-05-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_flow_triggers_and_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotflow',
            name='completion_message',
            field=models.TextField(blank=True, default='✅ Prontinho! Suas informações foram registradas. Um de nossos especialistas vai te chamar em breve.', help_text="Texto enviado ao final do fluxo (somente se 'Enviar mensagem ao concluir' estiver ativo).", verbose_name='Mensagem ao concluir'),
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='send_completion_message',
            field=models.BooleanField(default=False, help_text='Se ativo, envia a mensagem abaixo quando o cliente termina o fluxo. Se desativo, o fluxo encerra silenciosamente.', verbose_name='Enviar mensagem ao concluir'),
        ),
    ]
