# Generated by Django 3.2.25 on 2026-05-08 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_completion_message_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotstep',
            options={'ordering': ['codigo_hierarquico', 'order'], 'verbose_name': 'Passo do Chatbot', 'verbose_name_plural': 'Passos do Chatbot'},
        ),
        migrations.AddField(
            model_name='chatbotstep',
            name='codigo_hierarquico',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text="Calculado automaticamente (ex.: '1.2.3').", max_length=64, verbose_name='Código hierárquico'),
        ),
        migrations.AddField(
            model_name='chatbotstep',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='Profundidade na árvore (raiz = 0).', verbose_name='Nível'),
        ),
        migrations.AddField(
            model_name='chatbotstep',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Define o agrupamento hierárquico para visualização (1, 1.1, 1.2…).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chatbot.chatbotstep', verbose_name='Etapa pai'),
        ),
        migrations.AddField(
            model_name='chatbotstep',
            name='subordem',
            field=models.PositiveIntegerField(default=0, help_text='Posição dentro do agrupamento do pai (0, 1, 2…).', verbose_name='Subordem'),
        ),
        migrations.AddIndex(
            model_name='chatbotstep',
            index=models.Index(fields=['flow', 'parent'], name='chatbot_cha_flow_id_a2436c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotstep',
            index=models.Index(fields=['flow', 'codigo_hierarquico'], name='chatbot_cha_flow_id_f478a8_idx'),
        ),
    ]
