# Generated by Django 3.2.25 on 2026-05-08 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_service_type_catalog'),
        ('chatbot', '0008_step_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotchoice',
            name='servico',
            field=models.ForeignKey(blank=True, help_text='Quando o cliente escolhe esta opção, o serviço é salvo na sessão e usado em automações futuras (lead, proposta).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_choices', to='operations.servicetype', verbose_name='Serviço associado'),
        ),
    ]
