# Generated by Django 3.2.25 on 2026-05-12 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_servico_integration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotaction',
            options={'ordering': ['step_id', 'order', 'trigger'], 'verbose_name': 'Ação do Chatbot', 'verbose_name_plural': 'Ações do Chatbot'},
        ),
        migrations.AddField(
            model_name='chatbotaction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desative temporariamente sem perder a configuração.', verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='chatbotaction',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de execução dentro do passo (menor primeiro).', verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='chatbotaction',
            name='step',
            field=models.ForeignKey(blank=True, help_text="Se preenchido, a ação roda DURANTE a execução desta etapa (use trigger 'Ao executar este passo'). Se vazio, é uma ação global do fluxo (legado).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='chatbot.chatbotstep', verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='chatbotstep',
            name='node_type',
            field=models.CharField(choices=[('message', 'Mensagem'), ('question', 'Pergunta'), ('condition', 'Condição'), ('action', 'Ação automática')], default='message', help_text='Categoria visual do nó para futura UI de fluxo. Sem efeito no motor atual.', max_length=20, verbose_name='Tipo de nó (visual)'),
        ),
        migrations.AddField(
            model_name='chatbotstep',
            name='position_x',
            field=models.FloatField(default=0.0, verbose_name='Posição X (visual)'),
        ),
        migrations.AddField(
            model_name='chatbotstep',
            name='position_y',
            field=models.FloatField(default=0.0, verbose_name='Posição Y (visual)'),
        ),
        migrations.AddField(
            model_name='chatbotstep',
            name='visual_config',
            field=models.JSONField(blank=True, default=dict, help_text='Cor, ícone, etc. — usado por futuro builder visual.', verbose_name='Configuração visual'),
        ),
        migrations.AlterField(
            model_name='chatbotaction',
            name='action_type',
            field=models.CharField(choices=[('create_lead', 'Criar lead'), ('update_pipeline', 'Atualizar pipeline'), ('apply_tag', 'Aplicar tag'), ('link_servico', 'Vincular serviço pré-fixado'), ('register_event', 'Registrar evento'), ('send_email', 'Enviar e-mail'), ('send_whatsapp', 'Enviar WhatsApp'), ('create_task', 'Criar tarefa'), ('notify_user', 'Notificar usuário (legado)'), ('send_message', 'Enviar mensagem (legado)')], default='create_lead', max_length=20, verbose_name='Tipo de ação'),
        ),
        migrations.AlterField(
            model_name='chatbotaction',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Parâmetros específicos do tipo (JSON). Ex.: para \'apply_tag\', {"tag": "qualificado"}; para "send_email", {"to": "...", "subject": "..."}.', verbose_name='Configuração'),
        ),
        migrations.AlterField(
            model_name='chatbotaction',
            name='trigger',
            field=models.CharField(choices=[('on_step', 'Ao executar este passo'), ('on_complete', 'Ao completar o fluxo'), ('on_timeout', 'Timeout'), ('on_keyword', 'Palavra-chave')], default='on_complete', max_length=20, verbose_name='Gatilho'),
        ),
        migrations.AlterField(
            model_name='chatbotstep',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Marque quando esta etapa representar o fim oficial do atendimento automático. Ações automáticas configuradas para o passo ainda rodam, mas nenhum próximo passo é disparado.', verbose_name='Encerrar conversa neste passo'),
        ),
        migrations.AddIndex(
            model_name='chatbotaction',
            index=models.Index(fields=['flow', 'step', 'is_active', 'order'], name='chatbot_cha_flow_id_3010bf_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotaction',
            index=models.Index(fields=['flow', 'trigger', 'is_active'], name='chatbot_cha_flow_id_d70089_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatbotaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('step__isnull', False), ('trigger', 'on_step')), models.Q(('step__isnull', True), models.Q(('trigger', 'on_step'), _negated=True)), _connector='OR'), name='chatbot_action_step_trigger_consistency'),
        ),
    ]
