# Generated by Django 3.2.25 on 2026-05-12 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empresa_email_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0010_action_per_step_and_visual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotflow',
            name='use_visual_builder',
            field=models.BooleanField(default=False, help_text='Quando ativo, o fluxo é gerenciado pelo construtor visual e o executor lê graph_json da versão publicada.', verbose_name='Construtor visual'),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='current_node_id',
            field=models.CharField(blank=True, help_text='ID do nó atual no graph_json publicado (motor v2). Vazio para fluxos legados.', max_length=64, verbose_name='Nó atual (graph_json)'),
        ),
        migrations.AlterField(
            model_name='chatbotsession',
            name='current_step',
            field=models.ForeignKey(blank=True, help_text='Apontador legado para ChatbotStep (motor v1).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatbotstep', verbose_name='Passo atual'),
        ),
        migrations.CreateModel(
            name='ChatbotSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Identificador único dentro da empresa. Ex.: 'crm_api_key'.", max_length=80, verbose_name='Nome (slug)')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('value_encrypted', models.BinaryField(help_text='Conteúdo encriptado via Fernet. Nunca exibir em UI.', verbose_name='Valor (encriptado)')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chatbot_secrets', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_chatbotsecret_set', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Segredo do Chatbot',
                'verbose_name_plural': 'Segredos do Chatbot',
                'ordering': ['empresa', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('inbound', 'Recebida (usuário → bot)'), ('outbound', 'Enviada (bot → usuário)'), ('system', 'Sistema')], max_length=10, verbose_name='Direção')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Botões, anexos, raw provider data, metadados.', verbose_name='Payload extra')),
                ('node_id', models.CharField(blank=True, help_text="ID do nó no graph_json OU 'step_<pk>' para fluxos legados.", max_length=64, verbose_name='ID do nó')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatbotsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Mensagem do Chatbot',
                'verbose_name_plural': 'Mensagens do Chatbot',
                'ordering': ['session', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotFlowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(help_text='Sequencial por flow. Calculado automaticamente no save().', verbose_name='Número da versão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('archived', 'Arquivada')], default='draft', max_length=20, verbose_name='Status')),
                ('graph_json', models.JSONField(blank=True, default=dict, help_text='Estrutura {nodes, edges, viewport, metadata, schema_version}.', verbose_name='Grafo (graph_json)')),
                ('schema_version', models.PositiveSmallIntegerField(default=1, help_text='Versão do graph_v1 schema; incrementada em breaking changes.', verbose_name='Versão do schema')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='Lista de erros do último validate (ou [] se válido).', verbose_name='Erros de validação')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Última validação')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicada em')),
                ('notes', models.TextField(blank=True, help_text='Release notes opcionais (changelog interno).', verbose_name='Notas de versão')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chatbot_versions', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='chatbot.chatbotflow', verbose_name='Fluxo')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_chatbot_versions', to=settings.AUTH_USER_MODEL, verbose_name='Publicada por')),
            ],
            options={
                'verbose_name': 'Versão de Fluxo',
                'verbose_name_plural': 'Versões de Fluxo',
                'ordering': ['flow', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_id', models.CharField(blank=True, max_length=64, verbose_name='ID do nó')),
                ('event', models.CharField(choices=[('node_entered', 'Nó iniciado'), ('node_exited', 'Nó concluído'), ('action_executed', 'Ação executada'), ('validation_failed', 'Validação falhou'), ('api_call', 'Chamada de API'), ('error', 'Erro'), ('session_started', 'Sessão iniciada'), ('session_completed', 'Sessão concluída')], max_length=30, verbose_name='Evento')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Aviso'), ('error', 'Erro')], default='info', max_length=10, verbose_name='Nível')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='chatbot.chatbotsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Log de Execução',
                'verbose_name_plural': 'Logs de Execução',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='current_published_version',
            field=models.ForeignKey(blank=True, help_text='Atalho para o executor (evita lookup por status a cada turno).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chatbot.chatbotflowversion', verbose_name='Versão publicada atual'),
        ),
        migrations.AddConstraint(
            model_name='chatbotsecret',
            constraint=models.UniqueConstraint(fields=('empresa', 'name'), name='chatbot_secret_unique_name_per_empresa'),
        ),
        migrations.AddIndex(
            model_name='chatbotmessage',
            index=models.Index(fields=['session', 'created_at'], name='chatbot_cha_session_5ecdfc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotmessage',
            index=models.Index(fields=['direction', 'created_at'], name='chatbot_cha_directi_2a1a17_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotflowversion',
            index=models.Index(fields=['flow', 'status'], name='chatbot_cha_flow_id_3cafc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatbotflowversion',
            constraint=models.UniqueConstraint(fields=('flow', 'numero'), name='chatbot_flowversion_unique_numero'),
        ),
        migrations.AddConstraint(
            model_name='chatbotflowversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('flow',), name='chatbot_flowversion_one_draft_per_flow'),
        ),
        migrations.AddConstraint(
            model_name='chatbotflowversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('flow',), name='chatbot_flowversion_one_published_per_flow'),
        ),
        migrations.AddIndex(
            model_name='chatbotexecutionlog',
            index=models.Index(fields=['session', 'created_at'], name='chatbot_cha_session_1c1e70_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotexecutionlog',
            index=models.Index(fields=['level', '-created_at'], name='chatbot_cha_level_cbcb1a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotexecutionlog',
            index=models.Index(fields=['event', '-created_at'], name='chatbot_cha_event_da556e_idx'),
        ),
    ]
