# Generated by Django 3.2.25 on 2026-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_visual_builder_v1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotmessage',
            name='node_id',
            field=models.CharField(blank=True, db_index=True, help_text="ID do nó no graph_json OU 'step_<pk>' para fluxos legados.", max_length=64, verbose_name='ID do nó'),
        ),
    ]
