# Generated by Django 5.1.15 on 2026-05-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imap_fields'),
        ('chatbot', '0012_h_node_id_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotaction',
            name='action_type',
            field=models.CharField(choices=[('create_lead', 'Criar lead'), ('update_pipeline', 'Atualizar pipeline'), ('apply_tag', 'Aplicar tag'), ('link_servico', 'Vincular serviço pré-fixado'), ('register_event', 'Registrar evento'), ('send_email', 'Enviar e-mail'), ('send_whatsapp', 'Enviar WhatsApp'), ('send_proposal', 'Enviar proposta'), ('send_contract', 'Enviar contrato'), ('create_task', 'Criar tarefa'), ('notify_user', 'Notificar usuário (legado)'), ('send_message', 'Enviar mensagem (legado)')], default='create_lead', max_length=20, verbose_name='Tipo de ação'),
        ),
        migrations.AlterField(
            model_name='chatbotsecret',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa'),
        ),
    ]
