# Generated by Django 5.1.15 on 2026-05-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_add_send_proposal_contract_actions'),
        ('crm', '0011_leadtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotflow',
            name='session_timeout_message',
            field=models.TextField(blank=True, default='', help_text="Opcional: enviada quando o cliente volta a falar depois de muito tempo. Ex.: 'Olá de novo! Vamos recomeçar do início.'", verbose_name='Mensagem ao recomeçar após timeout'),
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Tempo sem resposta para expirar a sessão. Na próxima mensagem o fluxo recomeça do início. 0 = nunca expira.', verbose_name='Timeout de sessão (minutos)'),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Última atividade'),
        ),
        migrations.AddIndex(
            model_name='chatbotsession',
            index=models.Index(fields=['status', 'last_activity_at'], name='chatbot_cha_status_2a3474_idx'),
        ),
    ]
