# Generated by Django 5.1.15 on 2026-05-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_session_timeout_rv06'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsession',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text="Quando foi enviado o último 'Você está aí?' para o nó atual. Resetado quando o cliente responde.", null=True, verbose_name='Lembrete enviado em'),
        ),
    ]
