# Generated by Django 5.1.15 on 2026-05-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_reminder_sent_at_rv06'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotaction',
            name='action_type',
            field=models.CharField(choices=[('create_lead', 'Criar lead'), ('update_pipeline', 'Atualizar pipeline'), ('apply_tag', 'Aplicar tag'), ('link_servico', 'Vincular serviço cadastrado'), ('register_event', 'Registrar evento'), ('send_email', 'Enviar e-mail'), ('send_whatsapp', 'Enviar WhatsApp'), ('send_proposal', 'Enviar proposta'), ('send_contract', 'Enviar contrato'), ('create_task', 'Criar tarefa'), ('notify_user', 'Notificar usuário (legado)'), ('send_message', 'Enviar mensagem (legado)')], default='create_lead', max_length=20, verbose_name='Tipo de ação'),
        ),
    ]
