# Generated by Django 5.1.15 on 2026-05-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_rename_servico_cadastrado_rv06'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotflow',
            name='default_auto_end_on_timeout',
            field=models.BooleanField(default=False, help_text='Se True, atingir o timeout marca a sessão como COMPLETED (limpa). Se False, marca EXPIRED (próxima msg reinicia).', verbose_name='Encerrar automaticamente após inatividade'),
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='default_on_return_behavior',
            field=models.CharField(choices=[('continue', 'Continuar do ponto onde parou'), ('restart', 'Reiniciar fluxo do início')], default='continue', help_text='Quando o cliente volta após o lembrete: continua de onde parou ou reinicia.', max_length=10, verbose_name='Comportamento ao retornar (padrão)'),
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='default_reminder_unit',
            field=models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas')], default='minutes', max_length=10, verbose_name='Unidade do tempo padrão'),
        ),
        migrations.AddField(
            model_name='chatbotflow',
            name='default_reminder_value',
            field=models.PositiveIntegerField(blank=True, help_text='Quanto tempo aguardar antes do lembrete (fallback p/ blocos sem config própria).', null=True, verbose_name='Tempo padrão de lembrete'),
        ),
    ]
