# Generated by Django 3.2.25 on 2026-04-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('proposal', 'Proposta'), ('contract', 'Contrato'), ('work_order', 'Ordem de Serviço'), ('financial_entry', 'Lançamento Financeiro')], max_length=30)),
                ('entity_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('chatbot_to_lead', 'Chatbot → Lead'), ('lead_to_proposal', 'Lead → Proposta'), ('proposal_to_contract', 'Proposta → Contrato'), ('contract_to_work_order', 'Contrato → OS'), ('work_order_to_billing', 'OS → Financeiro'), ('full_pipeline', 'Pipeline Completo')], max_length=40)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], default='success', max_length=10)),
                ('source_entity_type', models.CharField(blank=True, max_length=30)),
                ('source_entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_automationlog_set', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Log de Automação',
                'verbose_name_plural': 'Logs de Automação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automationlog',
            index=models.Index(fields=['empresa', 'action'], name='automation__empresa_3db886_idx'),
        ),
        migrations.AddIndex(
            model_name='automationlog',
            index=models.Index(fields=['empresa', 'entity_type', 'entity_id'], name='automation__empresa_52660f_idx'),
        ),
    ]
