# Generated by Django 3.2.25 on 2026-05-08 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_backfill_contatos'),
        ('accounts', '0001_initial'),
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationlog',
            name='action',
            field=models.CharField(choices=[('chatbot_to_lead', 'Chatbot → Lead'), ('lead_to_proposal', 'Lead → Proposta'), ('proposal_to_contract', 'Proposta → Contrato'), ('contract_to_work_order', 'Contrato → OS'), ('work_order_to_billing', 'OS → Financeiro'), ('full_pipeline', 'Pipeline Completo'), ('proposal_pipeline_trigger', 'Proposta → Pipeline (regra)'), ('proposal_deleted', 'Proposta excluída')], max_length=40),
        ),
        migrations.CreateModel(
            name='PipelineAutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('event', models.CharField(choices=[('proposta_criada', 'Proposta criada'), ('proposta_enviada', 'Proposta enviada'), ('proposta_aceita', 'Proposta aceita'), ('proposta_rejeitada', 'Proposta rejeitada'), ('proposta_cancelada', 'Proposta cancelada'), ('proposta_expirada', 'Proposta expirada')], db_index=True, max_length=40, verbose_name='Evento')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativa')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Menor valor = maior prioridade. Empate vai por nome.', verbose_name='Prioridade')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_pipelineautomationrule_set', to='accounts.empresa')),
                ('target_pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_rules', to='crm.pipeline', verbose_name='Pipeline destino')),
                ('target_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_rules', to='crm.pipelinestage', verbose_name='Etapa destino')),
            ],
            options={
                'verbose_name': 'Regra de Automação',
                'verbose_name_plural': 'Regras de Automação',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='pipelineautomationrule',
            index=models.Index(fields=['empresa', 'event', 'is_active', 'priority'], name='automation__empresa_4ceeda_idx'),
        ),
    ]
