# Generated by Django 5.1.15 on 2026-05-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imap_fields'),
        ('automation', '0002_pipeline_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationlog',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa'),
        ),
        migrations.AlterField(
            model_name='pipelineautomationrule',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa'),
        ),
    ]
