# Generated by Django 5.1.15 on 2026-05-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_lead_won_finance_rv06'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineautomationrule',
            name='event',
            field=models.CharField(choices=[('proposta_criada', 'Proposta criada'), ('proposta_enviada', 'Proposta enviada'), ('proposta_aceita', 'Proposta aceita'), ('proposta_rejeitada', 'Proposta rejeitada'), ('proposta_cancelada', 'Proposta cancelada'), ('proposta_expirada', 'Proposta expirada'), ('contrato_criado', 'Contrato criado'), ('contrato_enviado', 'Contrato enviado'), ('contrato_assinado', 'Contrato assinado'), ('contrato_ativo', 'Contrato ativo'), ('contrato_concluido', 'Contrato concluído'), ('contrato_cancelado', 'Contrato cancelado'), ('os_criada', 'OS criada'), ('os_agendada', 'OS agendada'), ('os_iniciada', 'OS iniciada'), ('os_pausada', 'OS pausada'), ('os_concluida', 'OS concluída'), ('os_cancelada', 'OS cancelada'), ('lead_criado', 'Lead criado'), ('lead_ganho', 'Lead ganho (won)'), ('lead_perdido', 'Lead perdido (lost)')], db_index=True, max_length=40, verbose_name='Evento'),
        ),
    ]
