# Generated by Django 5.1.15 on 2026-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_expand_events_rv10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationlog',
            name='action',
            field=models.CharField(choices=[('chatbot_to_lead', 'Chatbot → Lead'), ('lead_to_proposal', 'Lead → Proposta'), ('proposal_to_contract', 'Proposta → Contrato'), ('contract_to_work_order', 'Contrato → OS'), ('work_order_to_billing', 'OS → Financeiro'), ('full_pipeline', 'Pipeline Completo'), ('proposal_pipeline_trigger', 'Proposta → Pipeline (regra)'), ('proposal_deleted', 'Proposta excluída'), ('contract_deleted', 'Contrato excluído')], max_length=40),
        ),
    ]
