# Generated by Django 5.1.15 on 2026-03-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('site', 'Site'), ('indicacao', 'Indicação'), ('google', 'Google'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Origem'),
        ),
    ]
