# Generated by Django 5.1.15 on 2026-03-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='external_ref',
            field=models.CharField(blank=True, help_text='ID externo (chatbot, API)', max_length=255, verbose_name='Referência Externa'),
        ),
    ]
