# Generated by Django 5.1.15 on 2026-04-20 17:58

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('crm', '0003_lead_external_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('phone', 'Ligação'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('meeting', 'Reunião'), ('chatbot', 'Chatbot'), ('other', 'Outro')], default='phone', max_length=20, verbose_name='Canal')),
                ('note', models.TextField(blank=True, verbose_name='Observação')),
                ('contacted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do contato')),
                ('external_ref', models.CharField(blank=True, help_text='ID externo (ex.: chatbot_session_id) para idempotência', max_length=255, verbose_name='Referência externa')),
            ],
            options={
                'verbose_name': 'Contato com Lead',
                'verbose_name_plural': 'Contatos com Leads',
                'ordering': ['-contacted_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, validators=[apps.core.validators.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='lead',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, validators=[apps.core.validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pipeline_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.pipelinestage', verbose_name='Etapa'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['empresa', 'current_stage', 'won_at'], name='crm_opportu_empresa_232283_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf', ''), _negated=True), fields=('empresa', 'cpf'), name='unique_cpf_per_empresa'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('empresa', 'cnpj'), name='unique_cnpj_per_empresa'),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa'),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.lead', verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddIndex(
            model_name='leadcontact',
            index=models.Index(fields=['empresa', 'lead'], name='crm_leadcon_empresa_3f2f78_idx'),
        ),
        migrations.AddIndex(
            model_name='leadcontact',
            index=models.Index(fields=['empresa', 'channel', 'contacted_at'], name='crm_leadcon_empresa_611210_idx'),
        ),
    ]
