# Generated by Django 5.1.15 on 2026-04-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_populate_lead_pipeline_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
    ]
