# Generated by Django 5.1.15 on 2026-05-07 13:38

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('crm', '0006_remove_lead_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead / Oportunidade', 'verbose_name_plural': 'Leads / Oportunidades'},
        ),
        migrations.RemoveConstraint(
            model_name='lead',
            name='unique_cpf_per_empresa',
        ),
        migrations.RemoveConstraint(
            model_name='lead',
            name='unique_cnpj_per_empresa',
        ),
        migrations.AddField(
            model_name='lead',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='contacts.contato', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, validators=[apps.core.validators.validate_cnpj], verbose_name='CNPJ (legado)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Empresa (legado)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, validators=[apps.core.validators.validate_cpf], verbose_name='CPF (legado)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail (legado)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome da Oportunidade'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone (legado)'),
        ),
    ]
