# Generated by Django 3.2.25 on 2026-05-08 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_service_type_catalog'),
        ('crm', '0008_backfill_contatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='operations.servicetype', verbose_name='Serviço Pré-Fixado'),
        ),
    ]
