# Generated by Django 5.1.15 on 2026-05-15 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imap_fields'),
        ('crm', '0010_lead_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=40, verbose_name='Tag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tags_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_applied', to='crm.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Tag de Lead',
                'verbose_name_plural': 'Tags de Leads',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['empresa', 'name'], name='crm_leadtag_empresa_23df6a_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'lead', 'name'), name='crm_leadtag_unique_per_lead')],
            },
        ),
    ]
