# Generated by Django 5.1.15 on 2026-05-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_leadtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor previsto do negócio. Usado para gerar entrada financeira automática quando o lead vai para uma etapa de ganho sem proposta aceita. Se vazio, usa o valor padrão do serviço vinculado.', max_digits=12, null=True, verbose_name='Valor estimado'),
        ),
    ]
