# Generated by Django 5.1.15 on 2026-06-02 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_rename_servico_cadastrado_rv06'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='crm.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Item do Checklist do Lead',
                'verbose_name_plural': 'Itens do Checklist do Lead',
                'ordering': ['order'],
            },
        ),
    ]
