# Generated by Django 5.1.15 on 2026-06-02 02:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_membership_job_role'),
        ('communications', '0006_alter_notification_type'),
        ('crm', '0014_leadchecklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('threshold_1_days', models.PositiveIntegerField(default=7, verbose_name='1º lembrete (dias)')),
                ('threshold_2_days', models.PositiveIntegerField(default=14, verbose_name='2º lembrete (dias)')),
                ('threshold_3_days', models.PositiveIntegerField(default=30, verbose_name='3º lembrete (dias)')),
                ('threshold_4_days', models.PositiveIntegerField(default=90, verbose_name='4º lembrete (dias)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
                ('user', models.ForeignKey(blank=True, help_text='NULL = padrão da empresa; preenchido = preferência do usuário.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Follow-up',
                'verbose_name_plural': 'Configurações de Follow-up',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'user'), name='uniq_followup_settings_empresa_user'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('empresa',), name='uniq_followup_empresa_default')],
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUpReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('threshold_days', models.PositiveIntegerField()),
                ('last_contact_at', models.DateTimeField()),
                ('notified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='crm.lead')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='communications.notification')),
            ],
            options={
                'verbose_name': 'Lembrete de Follow-up',
                'verbose_name_plural': 'Lembretes de Follow-up',
                'indexes': [models.Index(fields=['empresa', 'lead'], name='crm_leadfol_empresa_bd3e26_idx')],
                'constraints': [models.UniqueConstraint(fields=('lead', 'threshold_days', 'last_contact_at'), name='uniq_followup_lead_threshold_basis')],
            },
        ),
    ]
