# Generated by Django 5.1.15 on 2026-06-10 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_membership_job_role'),
        ('crm', '0015_followupsettings_leadfollowupreminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('lead_created', 'Lead criado'), ('proposal_sent', 'Proposta enviada'), ('proposal_accepted', 'Proposta aceita'), ('contract_sent', 'Contrato enviado'), ('contract_signed', 'Contrato assinado'), ('lead_moved', 'Mudança de etapa'), ('assignee_changed', 'Mudança de responsável'), ('service_started', 'Serviço iniciado'), ('service_completed', 'Serviço concluído'), ('lead_won', 'Fechado Ganho'), ('lead_lost', 'Fechado Perdido'), ('contact_logged', 'Contato registrado'), ('message_inbound', 'Mensagem recebida'), ('conversation_assigned', 'Conversa atribuída'), ('other', 'Evento')], default='other', max_length=40, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='Ícone')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Evento do Lead',
                'verbose_name_plural': 'Eventos do Lead',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='crm_leadeve_lead_id_b07e9f_idx'), models.Index(fields=['empresa', 'event_type'], name='crm_leadeve_empresa_352891_idx')],
            },
        ),
    ]
