# Generated by Django 5.1.15 on 2026-03-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='cloud_storage_links',
            field=models.JSONField(blank=True, default=list, help_text='Lista de links (Google Drive, Dropbox, etc.)', verbose_name='Links de Arquivos'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link Google Maps'),
        ),
    ]
