# Generated by Django 3.2.25 on 2026-05-08 23:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_backfill_contatos'),
        ('contracts', '0001_initial'),
        ('proposals', '0006_send_tracking_and_public_token'),
        ('operations', '0003_team_and_assigned_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['name'], 'verbose_name': 'Serviço Pré-Fixado', 'verbose_name_plural': 'Serviços Pré-Fixados'},
        ),
        migrations.AddField(
            model_name='servicetype',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Código curto opcional (ex.: TOPO-001).', max_length=40, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='default_contract_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_service_types', to='contracts.contracttemplate', verbose_name='Modelo de contrato padrão'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='default_description',
            field=models.TextField(blank=True, help_text='HTML rich-text. Usado em propostas/leads como sugestão.', verbose_name='Descrição padrão (rich)'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='default_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_service_types', to='crm.pipeline', verbose_name='Pipeline padrão'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='default_prazo_dias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo estimado (dias)'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Preço padrão'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='default_proposal_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_service_types', to='proposals.proposaltemplate', verbose_name='Modelo de proposta padrão'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='default_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_service_types', to='crm.pipelinestage', verbose_name='Etapa padrão'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='Observações internas'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='tags',
            field=models.CharField(blank=True, help_text='Separadas por vírgula (ex.: topografia, regularização).', max_length=255, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição interna'),
        ),
        migrations.AddIndex(
            model_name='servicetype',
            index=models.Index(fields=['empresa', 'category'], name='operations__empresa_9c88e1_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetype',
            index=models.Index(fields=['empresa', 'is_active'], name='operations__empresa_2fdad9_idx'),
        ),
    ]
