# Generated by Django 5.1.15 on 2026-05-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imap_fields'),
        ('operations', '0004_service_type_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa'),
        ),
    ]
