# Generated by Django 5.1.15 on 2026-05-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_lead_won_finance_rv06'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['name'], 'verbose_name': 'Serviço Cadastrado', 'verbose_name_plural': 'Serviços Cadastrados'},
        ),
    ]
