# Generated by Django 5.1.15 on 2026-05-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_rename_servico_cadastrado_rv06'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='expected_end_date',
            field=models.DateField(blank=True, help_text='Quando a OS deve terminar. Calculado a partir do prazo do serviço cadastrado, mas pode ser editado.', null=True, verbose_name='Previsão de término'),
        ),
    ]
