# Generated by Django 5.1.15 on 2026-06-02 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imap_fields'),
        ('operations', '0007_workorder_expected_end_date_rv10'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Função / Cargo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Função / Cargo',
                'verbose_name_plural': 'Funções / Cargos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HourRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('team', 'Equipe (padrão da empresa)'), ('user', 'Responsável (por usuário)'), ('job_role', 'Função / Cargo')], max_length=10, verbose_name='Escopo')),
                ('hourly_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor por hora (R$)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hour_rates', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hour_rates', to='operations.jobrole', verbose_name='Função / Cargo')),
            ],
            options={
                'verbose_name': 'Valor Hora',
                'verbose_name_plural': 'Valores Hora',
                'ordering': ['scope', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('timer', 'Cronômetro'), ('manual', 'Manual')], default='timer', max_length=10, verbose_name='Origem')),
                ('started_at', models.DateTimeField(verbose_name='Início')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Calculado ao parar o cronômetro ou no lançamento manual.', verbose_name='Duração (s)')),
                ('is_billable', models.BooleanField(default=True, verbose_name='Faturável')),
                ('rate_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor hora aplicado')),
                ('rate_source', models.CharField(blank=True, help_text='responsavel | funcao | equipe | (vazio = sem tarifa)', max_length=20, verbose_name='Origem da tarifa')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Observações')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_time_logs', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='operations.workorder', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Apontamento de Horas',
                'verbose_name_plural': 'Apontamentos de Horas',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobrole',
            constraint=models.UniqueConstraint(fields=('empresa', 'name'), name='uniq_jobrole_name_per_empresa'),
        ),
        migrations.AddConstraint(
            model_name='hourrate',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'team')), fields=('empresa',), name='uniq_team_rate_per_empresa'),
        ),
        migrations.AddConstraint(
            model_name='hourrate',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'user')), fields=('empresa', 'user'), name='uniq_user_rate_per_empresa'),
        ),
        migrations.AddConstraint(
            model_name='hourrate',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'job_role')), fields=('empresa', 'job_role'), name='uniq_jobrole_rate_per_empresa'),
        ),
        migrations.AddIndex(
            model_name='workordertimelog',
            index=models.Index(fields=['work_order', 'ended_at'], name='operations__work_or_7a2fd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='workordertimelog',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('work_order', 'user'), name='uniq_running_timer_per_user_wo'),
        ),
        migrations.AddConstraint(
            model_name='workordertimelog',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='timelog_end_after_start'),
        ),
    ]
