# Generated by Django 5.1.15 on 2026-06-02 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_jobrole_hourrate_workordertimelog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workordertimelog',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('user__isnull', True)), fields=('work_order',), name='uniq_running_timer_null_user_wo'),
        ),
    ]
