# Generated by Django 5.1.15 on 2026-06-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_workordertimelog_uniq_running_timer_null_user_wo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='google_event_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='ID do evento no Google'),
        ),
    ]
