# Generated by Django 5.1.15 on 2026-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_workorder_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='google_drive_folder_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='ID da pasta no Google Drive'),
        ),
    ]
